### ISSUE TITLE
Over-localization of Razor-Pages

### ISSUE THREAD

**Issue by JuergenGutsch** [aspnet/Docs.de-de#12]
The term "Razor-pages" shouldn't be translated into "Razor-Seiten".
e.g. https://docs.microsoft.com/de-de/aspnet/core/tutorials/razor-pages/

Germans usually don't translate identifier and names. In this case Razor-Pages is a name of a Technologie. So it is absolutely fine to not translate Razor-Pages-Web-App into Razor-Seiten-Web-App.

I would take care of the fix, if you agree.

**Comment by mairaw** [comment]
@nokura can you provide feedback on this issue?

**Comment by nokura** [comment]
I am addressing this input to our internal linguistic team. I will get back when the decision is made.
I would appreciate your PR for this kind of linguistic issue as it will be sent directly to the linguist team and can be processed faster.

**Comment by JuergenGutsch** [comment]
Hi @nokura 
great thanks.
I already created the PR: #14

**Comment by CeciAc** [comment]
Closing this issue, solved through mentioned PR
