### ISSUE TITLE
Content: Codesnipped is not shown

### ISSUE THREAD

**Issue by qjubic** [aspnet/Docs.de-de#23]
Instead of actual code there is a line with "[!code-csharp]".

URL: https://docs.microsoft.com/de-de/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-2.1

![image](https://user-images.githubusercontent.com/25281537/42727612-762d8ccc-87aa-11e8-8107-03e07ed189c2.png)

**Comment by gosali** [comment]
Hello, @qjubic , 
 

Thank you for your feedback. 
We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @qjubic ,

Thank you for your feedback. 
  
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/aspnet/core/tutorials/first-mvc-app/controller-methods-views?view=aspnetcore-2.1.  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
