### ISSUE TITLE
Typo in german Navigation

### ISSUE THREAD

**Issue by jhueppauff** [aspnet/Docs.de-de#24]
It seems there is a typo in the german side Navigation.
I think it should be called "DSVGO" not "GSGVO". 

The Page Title itself seems to be correct, just the Navigation states the error.

![grafik](https://user-images.githubusercontent.com/20532954/42728345-5b787e4c-87b8-11e8-9694-184c407b4463.png)

**Comment by gosali** [comment]
Hello, @jhueppauff , 

 Thank you for your feedback. 
We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @jhueppauff 
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published.
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
