### ISSUE TITLE
How to test this in combination with authorization?

### ISSUE THREAD

**Issue by ChristianSauer** [aspnet/Docs.de-de#34]
I think most controllers of the world are protected by some form of authorization.
But how to add this in this case?
I would have to assign to controller.User, but that is read only

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b5cce372-24e2-3489-cb19-c85d934e5d3b
* Version Independent ID: 9d12b19f-a94e-4df4-357b-3f3b93696eb6
* Content: [Testen von Controllerlogik in ASP.NET Core](https://docs.microsoft.com/de-de/aspnet/core/mvc/controllers/testing?view=aspnetcore-2.2)
* Content Source: [aspnetcore/mvc/controllers/testing.md](https://github.com/aspnet/docs.de-de/blob/live/aspnetcore/mvc/controllers/testing.md)
* Product: **aspnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by LisandroSu** [comment]
Hello, @ChristianSauer 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by ChristianSauer** [comment]
Hi,
I still think this is also a doc issue.
It is the most fundamental think to solve and should be spelled out in the docs.
