### ISSUE TITLE
Linux: LocalDB not supported!

### ISSUE THREAD

**Issue by bashdx** [aspnet/Docs.de-de#35]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Hinzufügen eines Modells zu einer App mit Razor-Seiten in ASP.NET Core](https://docs.microsoft.com/de-de/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/docs.de-de/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

I was working through the tutorial on my Ubuntu using VS Code. When I hit the "testing" step after scaffolding the CRUD pages, I get the error "PlatformNotSupportedException: LocalDB is not supported on this platform." This is fine, but no workaround (like possibly using SQLite 3) is mentioned.

Edit: Used SQLite instead
- dotnet add package Microsoft.EntityFrameworkCore.Sqlite
- added services.AddDbContext<RazorPagesMovieContext>(options =>
                    options.UseSqlite("Data Source=Movies.db")); to Startup.cs
- created an initial migration and updated DB using dotnet ef

**Comment by Rick-Anderson** [comment]
https://docs.microsoft.com/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio-code#add-a-database-connection-string

**Comment by bashdx** [comment]
@Rick-Anderson 

Thank you for the hint. But the link you posted this is where I came from. It does not mention that LocalDB is not available on Linux. Neither is the article suggesting any work around.

**Comment by Rick-Anderson** [comment]
The directions for VSCode and VSmac have you use SQLite, not LocalDB.

**Comment by CeciAc** [comment]
Hello, @bashdx 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
