### ISSUE TITLE
For developers from Germany the price cannot be a decimal number

### ISSUE THREAD

**Issue by vonwenckstern** [aspnet/Docs.de-de#37]
If I enter in the `Price` field the value `12,54` I receive the error `The field Price must be a number`. If I enter in the `Price` field the value `12.54` the price in the overview list is displayed as `1254,00`.

See:
* https://1drv.ms/u/s!Ah6SgCBWaM9n4XoGtRHj8-Tk-rdQ
![19 04 18 ErrorNumber](https://user-images.githubusercontent.com/30497492/56377197-20bd9080-620a-11e9-94bb-9bf9c53779e8.png)
* https://1drv.ms/u/s!Ah6SgCBWaM9n4Xt_RBUwym-Rf_wT
![19 04 18 ErrorNumber2](https://user-images.githubusercontent.com/30497492/56377206-287d3500-620a-11e9-8990-cd87d882c842.png)

Exist there a way to specify the seperator of the `decimal` type in the model via an annotation?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6719f08e-3bd7-dc1a-71df-f2ef9fbca9d8
* Version Independent ID: 7096fdb3-612e-9e00-bd0b-8ea4886a09ce
* Content: [Hinzufügen eines Modells zu einer App mit Razor-Seiten in ASP.NET Core](https://docs.microsoft.com/de-de/aspnet/core/tutorials/razor-pages/model?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/razor-pages/model.md](https://github.com/aspnet/Docs.de-de/blob/live/aspnetcore/tutorials/razor-pages/model.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
Per Artikel:

 Hinweis

Sie können unter Umständen in das Feld Price keine Kommas als Dezimaltrennzeichen eingeben. Zur Unterstützung der jQuery-Validierung für Gebietsschemas mit einer anderen Sprache als Englisch, in denen ein Komma („,“) als Dezimaltrennzeichen verwendet wird, und für Datums- und Uhrzeitformate, die nicht dem US-englischen Format entsprechen, muss die App globalisiert werden. Globalisierungsanweisungen finden Sie unter GitHub-Problem.


Empfehlen Sie dieses Problem.

**Comment by CeciAc** [comment]
Hello, @vonwenckstern 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
